[package]
name = "midi_pulse"
version = "0.1.0"
edition = "2021"

[lib]
path = "code/rust/midi_pulse/lib.rs"

[[bin]]
name = "polite_ping"
path = "code/rust/demos/polite_ping.rs"

[[bin]]
name = "add_echo"
path = "code/rust/demos/add_echo.rs"

[[bin]]
name = "sampler"
path = "code/rust/sampler/sampler.rs"

[[bin]]
name = "edo72"
path = "code/rust/edo72/edo72.rs"

[[bin]]
name = "triangle_chord"
path = "code/rust/synth/triangle_chord.rs"

[dependencies]
midir = "0.10"
minifb = "0.27"
