[package]
name = "midi_pulse"
version = "0.1.0"
edition = "2021"

[lib]
path = "code/rust/midi_pulse/lib.rs"

[[bin]]
name = "polite_ping"
path = "code/rust/demos/polite_ping.rs"

[[bin]]
name = "add_echo"
path = "code/rust/demos/add_echo.rs"

[[bin]]
name = "sampler"
path = "code/rust/sampler/sampler.rs"

[[bin]]
name = "edo12n_piano"
path = "code/rust/edo12n_piano/edo12n_piano.rs"

[[bin]]
name = "edo12n_piano_monome"
path = "code/rust/edo12n_piano_monome/edo12n_piano_monome.rs"

[[bin]]
name = "edo_un12_piano_monome"
path = "code/rust/edo_un12_piano_monome/edo_un12_piano_monome.rs"

[[bin]]
name = "triangle_chord"
path = "code/rust/synth/triangle_chord.rs"

[dependencies]
midir = "0.10"
minifb = "0.27"
rosc = "0.10"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
