* constraint both the composition and the music interface
** TODO NEXT : unified storage actions for sustain/chords
needs all of these
*** NEXT: accretion without storage
**** types
***** 'accretion slot' = a vector of edo pitches
These are unconstrained integers.
If the edo is 46, then 46 is an octave above 0, etc.
There will only be one accretion slot in the app
(until we add chord storage), but it still deserves its own type.
***** "toggle buttons"
Press it once to turn it on.
Press it again to turn it off.
Removing finger, in both cases, does nothing.
***** "ephemeral buttons"
This is the other option to "toggle button".
An ephemeral button is only on -- both emitting light,
and doing whatever the light emission signifiies -- while depressed.
Finger down turns it on; finger up turns it off.
***** "toggleness toggle buttons"
These buttons are dedicated merely to
choosing whether another button is toggle or ephemeral.
***** "ephemeral-or-toggle button"
A button B is ephemeral-or-toggle
if some corresponding "toggleness toggle button" T
determines whether B is toggle or not.
(Such button T is always toggle, never ephemeral.)
**** four special buttons
***** 'accretion-accrete' button
When accretion-ingest is on,
notes played in the main edo region accrete into the slot.
Each note-on writes to the slot.
Each note-off does not affect the slot.
Notes that were already being held when accretion-ingest turned on
are not accreted.
***** 'accretion-emit' button
Pressing this button makes the accretion sound,
and lights up every corresponding button in the main edo grid region.
  (As with ordinary notes played live,
  any key enharmonically equivalent (regardless of octave)
  to any note in the accretion slot should light up.
***** 'accretion-silent' button
****** what it does
Pressing this button makes the accretion stop sounding if it was.
****** Why this is distinct from 'accretion-silent'
will become apparent once chord storage is added.
***** 'accretion-wipe' button
Pressing this resets the accretion slot to the empty vector.
If it was playing, it should stop.
*** storage
**** silence (already implemented)
is like a permanent stored empty chord button.
Unlike the others chord buttons, it cannot be written to.
**** chord buttons
Some buttons are where chords can be stored.
One chord per button.
Call these the chord buttons.
**** the button being accreted to can be on or off
If it's on, the accretions continue ringing after finger-off.
This unifies sustain and chord storage.
*** a volume control for the stored chords
Critical, for the melody to stand out.
** the whole vision, but disorganized
*** chord storage
**** detail
***** The major playing area is an edo grid.
***** Some smaller ones are for storage:
**** initial vision
Store a chord to a button,
change the {volume,..} of the stored chords,
play them. The notes they correspond to show.
*** melody-chord symmetry
For both the finger-sounding notes and the stored chords,
some buttons are presets (at least 8),
some control the dimension being varied,
and some (a row of 8, say) control the value along that dimension.
That is, there are two (finger and stored) windows of three
(presets, dimensions, value).
Oh wait no a fourth, the record/accrete/store/save actions.
** more fun ideas
*** record short "vibrato loops" of the parameter values
* [[./code/edo72/requests/visual-feedback.org][72-edo-from-12 visual feedback]]
* [[id:beefb9cf-7378-4e75-9cd4-d868ea065092][monome haskell : build each note and map it to the keys]]
* synth plans
** maybe don't choose algorithms (e.g. sine) ahead of time; just pick the easiest initially, and optimize only if profiling identifies it as important
* dubstep
** special keys are for changing timbre
** make a scide synth with momentum
* sampler
** 1
Based on the other two files in code/, let's make a sampler.
This should echo to one output immediately,
while the other is only used when samples are triggered.
The two highest notes on the keyboard will be repurposed;
they do not correspond to notes but to actions.
In particular, the highest one is to trigger,
and the second highest one is to record.
Let's call those keys highest-c and highest-b.

There will for now be at most only one recorded clip in memory at once.
As soon as highest-b is pressed (note on), recording begins.
It continues until highest-b or -c is again played (note on).
If it's highest-b, recording ends and that's all.
If it's instead highest-c, recording ends and playback begins.

Let's modify that a little, though: If there was a note-on or note-off event from the normal keys within the last 50 ms, the recording time is moved back to that moment.
** 2
It needs complication. The loop should run forever. That means I need a third button. I renamed the top two keys to TOP_*. Let's add TOP_BFLAT, which ends the loop.

We also need to worry about note offs. Ending the loop should terminate all notes that would be otherwise left ringing.
** document it
*** top-bflat: if recording is going, it ends.
    if playback is going, it ends.
*** top-b: start, stop recording
*** top-c: start playback (and stop recording if applicable)
* arpeggiator
** one hand plays pattern
** one hand chooses notes
** playing is constrained to within the choice
** record and trigger
   three highest keys are to record to a place and
                          to play from a place
                          to stop that playback
   next few keys below are the places
** hard: the map from melody onto chosen pitch constraint
* scale display
  Print scales to screen. Maybe name them randomly.
* scale save
  on laptop, press 's' followed by any character
* scale recall
  on laptop, press 'r' followed by any character
* silent scale input
  Hold a chord with sustain pedal.
  Press a key to pause the echo behavior.
  With practice, a 7-tone scale consisting of two chains of fifths
  will be enterable in under a second. In serial:
    - right hand plays first shift
    - left hand plays the notes with that shift
    - right hand plays the second shift
    - left hand plays the notes with that shift
* record scale to reaper
* play back scale from reaper
* All note-specific shifts are absolute, i.e. idempotent.
  Shifting a note up 2\72, and then doing it again,
  is just like shifting it up 2\72 once.
