* 72-EDO MIDI transformer
* purpose
** in the abstract
Transforms MIDI notes from a piano keyboard
into multi-channel output for 72-EDO tuning.
There are twelve microtonal shifts,
one for each note modulo octave.
They all start at 0 and can be changed by +/- 6\72.
While one presses a shift value from the shift octave,
every note-on from the other octaves is shifted that much.
** how to play it
*** recognize on screen the value at a root
*** retune other things in terms of it
* using it
** to start it
*** Connect the keyboard.
*** Start the docker container.
    See [[../../docker.sh]].
*** In the host system, allow the container to open an X11 window:
    xhost +local:
    The container also needs =/tmp/.X11-unix= mounted, =DISPLAY= set, and
    X11 runtime libraries on =LD_LIBRARY_PATH=; the current Docker image
    definition in =docker-typedb-rust/docker.nix= provides the library path.
*** In the docker container, from the project root, run
    cargo run --bin edo72
*** In the host system, run
    ./code/edo72/connect-midi.sh
** to configure it
Be sure the 'const' definitions in the code make sense --
they depend on the synth being used.
* the math and specific values
For each piano note (21-96):
- Subtract lowest A (21) to get 0-75
- divmod by 12
  - quotient -> channel offset,
  - remainder -> note offset
- Add those offsets to min_channel and min_note
  (The earlier channel value is discarded.)

The top octave = 13 keys, notes 97-108, C#7 to C8
- F#7 (102) = 0 offset (12-EDO)
- G7 (103) = +1, G#7 = +2, ... C8 (108) = +6
- F7 (101) = -1, E7 = -2, ... C#7 (97) = -5
This offset is added to the output note, shifting all played notes.
